// Curated seed of US campuses with their verified .edu domains.
// Production should import the full ~4,000-school list from the US Dept. of
// Education IPEDS dataset; this subset gets you running and demoable.
// Schools with an empty `domains` array accept any .edu during signup.
export const SCHOOLS = [
  { name: 'New York University', short: 'NYU', domains: ['nyu.edu'] },
  { name: 'Columbia University', short: null, domains: ['columbia.edu'] },
  { name: 'Cornell University', short: null, domains: ['cornell.edu'] },
  { name: 'Harvard University', short: null, domains: ['harvard.edu', 'college.harvard.edu'] },
  { name: 'Massachusetts Institute of Technology', short: 'MIT', domains: ['mit.edu'] },
  { name: 'Stanford University', short: null, domains: ['stanford.edu'] },
  { name: 'University of California, Berkeley', short: 'UC Berkeley', domains: ['berkeley.edu'] },
  { name: 'University of California, Los Angeles', short: 'UCLA', domains: ['ucla.edu', 'g.ucla.edu'] },
  { name: 'University of California, San Diego', short: 'UCSD', domains: ['ucsd.edu'] },
  { name: 'University of Southern California', short: 'USC', domains: ['usc.edu'] },
  { name: 'University of Michigan', short: 'UMich', domains: ['umich.edu'] },
  { name: 'University of Texas at Austin', short: 'UT Austin', domains: ['utexas.edu'] },
  { name: 'University of Washington', short: 'UW', domains: ['uw.edu', 'washington.edu'] },
  { name: 'University of Illinois Urbana-Champaign', short: 'UIUC', domains: ['illinois.edu'] },
  { name: 'Georgia Institute of Technology', short: 'Georgia Tech', domains: ['gatech.edu'] },
  { name: 'University of Florida', short: 'UF', domains: ['ufl.edu'] },
  { name: 'Pennsylvania State University', short: 'Penn State', domains: ['psu.edu'] },
  { name: 'Ohio State University', short: 'OSU', domains: ['osu.edu', 'buckeyemail.osu.edu'] },
  { name: 'University of Wisconsin–Madison', short: 'UW–Madison', domains: ['wisc.edu'] },
  { name: 'University of Pennsylvania', short: 'UPenn', domains: ['upenn.edu', 'seas.upenn.edu'] },
  { name: 'Carnegie Mellon University', short: 'CMU', domains: ['cmu.edu', 'andrew.cmu.edu'] },
  { name: 'Boston University', short: 'BU', domains: ['bu.edu'] },
  { name: 'Northeastern University', short: null, domains: ['northeastern.edu', 'husky.neu.edu'] },
  { name: 'New York University Stern', short: 'Stern', domains: ['stern.nyu.edu'] },
  { name: 'Arizona State University', short: 'ASU', domains: ['asu.edu'] },
  { name: 'Purdue University', short: null, domains: ['purdue.edu'] },
  { name: 'University of Michigan–Dearborn', short: null, domains: ['umich.edu'] },
  { name: 'Rutgers University', short: null, domains: ['rutgers.edu', 'scarletmail.rutgers.edu'] },
  { name: 'University of Maryland', short: 'UMD', domains: ['umd.edu', 'terpmail.umd.edu'] },
  { name: 'University of North Carolina at Chapel Hill', short: 'UNC', domains: ['unc.edu', 'ad.unc.edu'] },
  { name: 'Duke University', short: null, domains: ['duke.edu'] },
  { name: 'University of Virginia', short: 'UVA', domains: ['virginia.edu'] },
  { name: 'Virginia Tech', short: 'VT', domains: ['vt.edu'] },
  { name: 'Michigan State University', short: 'MSU', domains: ['msu.edu'] },
  { name: 'University of Minnesota', short: 'UMN', domains: ['umn.edu'] },
  { name: 'Indiana University Bloomington', short: 'IU', domains: ['iu.edu', 'indiana.edu'] },
  { name: 'University of Colorado Boulder', short: 'CU Boulder', domains: ['colorado.edu'] },
  { name: 'University of Arizona', short: null, domains: ['arizona.edu'] },
  { name: 'University of Georgia', short: 'UGA', domains: ['uga.edu'] },
  { name: 'Texas A&M University', short: 'TAMU', domains: ['tamu.edu'] },
  { name: 'University of Notre Dame', short: null, domains: ['nd.edu'] },
  { name: 'Yale University', short: null, domains: ['yale.edu'] },
  { name: 'Princeton University', short: null, domains: ['princeton.edu'] },
  { name: 'Brown University', short: null, domains: ['brown.edu'] },
  { name: 'University of Chicago', short: 'UChicago', domains: ['uchicago.edu'] },
  { name: 'Northwestern University', short: null, domains: ['northwestern.edu', 'u.northwestern.edu'] },
  { name: 'Washington University in St. Louis', short: 'WashU', domains: ['wustl.edu'] },
  { name: 'University of Miami', short: null, domains: ['miami.edu'] },
  { name: 'Florida State University', short: 'FSU', domains: ['fsu.edu'] },
  { name: 'San Diego State University', short: 'SDSU', domains: ['sdsu.edu'] },
  { name: 'San José State University', short: 'SJSU', domains: ['sjsu.edu'] },
  { name: 'California Polytechnic State University, SLO', short: 'Cal Poly', domains: ['calpoly.edu'] },
  { name: 'University of Oregon', short: 'UO', domains: ['uoregon.edu'] },
  { name: 'University of Utah', short: null, domains: ['utah.edu', 'umail.utah.edu'] },
  { name: 'University of Pittsburgh', short: 'Pitt', domains: ['pitt.edu'] },
  { name: 'Syracuse University', short: null, domains: ['syr.edu'] },
  { name: 'Tulane University', short: null, domains: ['tulane.edu'] },
  { name: 'Vanderbilt University', short: null, domains: ['vanderbilt.edu'] },
  { name: 'Emory University', short: null, domains: ['emory.edu'] },
  { name: 'Rice University', short: null, domains: ['rice.edu'] },
  { name: 'University of Kansas', short: 'KU', domains: ['ku.edu'] },
];
